version: '3'

services:
  clinic-app:
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres
      NODE_ENV: ${NODE_ENV}
      PORT: 8080
      JWT_SECRET: ${JWT_SECRET}
    platform: linux/amd64
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: 'feebsk268/clinic-app:latest'
    ports:
      - '8080:8080'
  postgres:
    image: 'postgres:13'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data