version: '3.8'

services:
  clinic-app:
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
      - NODE_ENV=${NODE_ENV}
      - PORT=8080
      - JWT_SECRET=${JWT_SECRET}
    platform: linux/amd64
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: ./
      dockerfile: Dockerfile
    image: 'clinic-app:latest'
    ports:
      - '8080:8080'
    networks:
      - clinic-network

  postgres:
    image: 'postgres:13'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - clinic-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

networks:
  clinic-network:
    external: true
