import { Knex } from "knex";
import { hashPassword } from "../utils/hash";
import { faker } from "@faker-js/faker";

export async function seed(knex: Knex): Promise<void> {
  //must need to have this command (it's for search bar function)
  // await knex.raw("CREATE EXTENSION pg_trgm;");

  // Deletes ALL existing entries
  faker.seed(1)
  await knex("notification").del();

  await knex("drug_instruction").del();
  await knex("diagnosis").del();
  await knex("patient").del();
  await knex("medicine").del();
  await knex("doctor").del();
  await knex("drug_shape").del();

  // Inserts seed entries
  await knex("drug_shape").insert([
    { shape: "Oval" },
    { shape: "Round" },
    { shape: "Capsule" },
    { shape: "Tablet" },
  ]);

  await knex("doctor").insert([
    {
      name: "Dr. John Doe",
      specialty: "General Practitioner",
      username: "doctor1",
      password: await hashPassword("password1"),
    },
    {
      name: "Dr. Jane Smith",
      specialty: "Cardiologist",
      username: "doctor2",
      password: await hashPassword("password2"),
    },
  ]);

  await knex("medicine").insert([
    {
      name: "Metformin",
      generic_drug: "Metformin Hydrochloride",
      description: "Used to treat type 2 diabetes.",
      dosage: 500,
      unit_measurement: "mg",
      type: "Oral",
      drug_shape_id: 4,
      color: "White",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Lisinopril",
      generic_drug: "Lisinopril",
      description: "Used to treat high blood pressure and heart failure.",
      dosage: 10,
      unit_measurement: "mg",
      type: "Oral",
      drug_shape_id: 1,
      color: "White",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Amoxicillin",
      generic_drug: "Amoxicillin",
      description: "Antibiotic used to treat various bacterial infections.",
      dosage: 500,
      unit_measurement: "mg",
      type: "Oral",
      drug_shape_id: 2,
      color: "Capsule: Yellow/White; Tablet: White",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Ibuprofen",
      generic_drug: "Ibuprofen",
      description: "Pain reliever and anti-inflammatory.",
      dosage: 200,
      unit_measurement: "mg",
      type: "Oral",
      drug_shape_id: 4,
      color: "White",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Simvastatin",
      generic_drug: "Simvastatin",
      description: "Lowers cholesterol levels.",
      dosage: 20,
      unit_measurement: "mg",
      type: "Oral",
      drug_shape_id: 4,
      color: "Light Yellow",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Hydrochlorothiazide",
      generic_drug: "Hydrochlorothiazide",
      description: "Diuretic used to treat high blood pressure and edema.",
      dosage: 25,
      unit_measurement: "mg",
      type: "Oral",
      drug_shape_id: 1,
      color: "White",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Metoprolol",
      generic_drug: "Metoprolol Tartrate",
      description: "Beta-blocker used to treat high blood pressure and angina.",
      dosage: 50,
      unit_measurement: "mg",
      type: "Oral",
      drug_shape_id: 4,
      color: "White",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Levothyroxine",
      generic_drug: "Levothyroxine Sodium",
      description: "Used to treat hypothyroidism.",
      dosage: 100,
      unit_measurement: "mcg",
      type: "Oral",
      drug_shape_id: 1,
      color: "White",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Losartan",
      generic_drug: "Losartan Potassium",
      description: "Used to treat high blood pressure and diabetic kidney disease.",
      dosage: 50,
      unit_measurement: "mg",
      type: "Oral",
      drug_shape_id: 4,
      color: "Tan",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Amlodipine",
      generic_drug: "Amlodipine Besylate",
      description: "Calcium channel blocker used to treat high blood pressure and angina.",
      dosage: 5,
      unit_measurement: "mg",
      type: "Oral",
      drug_shape_id: 4,
      color: "White",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Sertraline",
      generic_drug: "Sertraline Hydrochloride",
      description: "Antidepressant used to treat depression and anxiety disorders.",
      dosage: 50,
      unit_measurement: "mg",
      type: "Oral",
      drug_shape_id: 1,
      color: "White",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Omeprazole",
      generic_drug: "Omeprazole",
      description: "Proton pump inhibitor used to treat acid reflux and stomach ulcers.",
      dosage: 20,
      unit_measurement: "mg",
      type: "Oral",
      drug_shape_id: 4,
      color: "White",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Atenolol",
      generic_drug: "Atenolol",
      description: "Beta-blocker used to treat high blood pressure and angina.",
      dosage: 50,
      unit_measurement: "mg",
      type: "Oral",
      drug_shape_id: 4,
      color: "White",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Fluoxetine",
      generic_drug: "Fluoxetine Hydrochloride",
      description: "Antidepressant used to treat depression, anxiety, and obsessive-compulsive disorder.",
      dosage: 20,
      unit_measurement: "mg",
      type: "Oral",
      drug_shape_id: 1,
      color: "Capsule: Green/White; Tablet: White",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Gabapentin",
      generic_drug: "Gabapentin",
      description: "Used to treat nerve pain, seizures, and certain types of anxiety.",
      dosage: 300,
      unit_measurement: "mg",
      type: "Oral",
      drug_shape_id: 4,
      color: "White",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Citalopram",
      generic_drug: "Citalopram Hydrobromide",
      description: "Antidepressant used to treat depression and anxiety disorders.",
      dosage: 20,
      unit_measurement: "mg",
      type: "Oral",
      drug_shape_id: 1,
      color: "White",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Alprazolam",
      generic_drug: "Alprazolam",
      description: "Benzodiazepine used to treat anxiety and panic disorders.",
      dosage: 0.5,
      unit_measurement: "mg",
      type: "Oral",
      drug_shape_id: 1,
      color: "White",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Clonazepam",
      generic_drug: "Clonazepam",
      description: "Benzodiazepine used to treat seizures, anxiety, and certain types of movement disorders.",
      dosage: 0.5,
      unit_measurement: "mg",
      type: "Oral",
      drug_shape_id: 1,
      color: "White",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Escitalopram",
      generic_drug: "Escitalopram Oxalate",
      description: "Antidepressant used to treat depression and anxiety disorders.",
      dosage: 10,
      unit_measurement: "mg",
      type: "Oral",
      drug_shape_id: 1,
      color: "White",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Duloxetine",
      generic_drug: "Duloxetine Hydrochloride",
      description: "Antidepressant used to treat depression, anxiety, and certain types of nerve pain.",
      dosage: 30,
      unit_measurement: "mg",
      type: "Oral",
      drug_shape_id: 1,
      color: "Green/White",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Venlafaxine",
      generic_drug: "Venlafaxine Hydrochloride",
      description: "Antidepressant used to treat depression, anxiety, and certain types of nerve pain.",
      dosage: 75,
      unit_measurement: "mg",
      type: "Oral",
      drug_shape_id: 4,
      color: "White",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Diclofenac",
      generic_drug: "Diclofenac Sodium",
      description: "NSAID used to reduce inflammation and relieve pain.",
      dosage: 50,
      unit_measurement: "mg",
      type: "Oral",
      drug_shape_id: 4,
      color: "Light Yellow",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Lamotrigine",
      generic_drug: "Lamotrigine",
      description: "Anticonvulsant used to treat seizures and bipolar disorder.",
      dosage: 25,
      unit_measurement: "mg",
      type: "Oral",
      drug_shape_id: 4,
      color: "White",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Levetiracetam",
      generic_drug: "Levetiracetam",
      description: "Anticonvulsant used to treat seizures.",
      dosage: 500,
      unit_measurement: "mg",
      type: "Oral",
      drug_shape_id: 4,
      color: "Blue",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Topiramate",
      generic_drug: "Topiramate",
      description: "Anticonvulsant used to treat seizures and migraines.",
      dosage: 25,
      unit_measurement: "mg",
      type: "Oral",
      drug_shape_id: 4,
      color: "White",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Rosuvastatin",
      generic_drug: "Rosuvastatin Calcium",
      description: "Statin used to lower cholesterol levels.",
      dosage: 10,
      unit_measurement: "mg",
      type: "Oral",
      drug_shape_id: 4,
      color: "Pink",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Pregabalin",
      generic_drug: "Pregabalin",
      description: "Used to treat nerve pain, seizures, and certain types of anxiety.",
      dosage: 75,
      unit_measurement: "mg",
      type: "Oral",
      drug_shape_id: 4,
      color: "White",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Pantoprazole",
      generic_drug: "Pantoprazole Sodium",
      description: "Proton pump inhibitor used to treat acid reflux and stomach ulcers.",
      dosage: 40,
      unit_measurement: "mg",
      type: "Oral",
      drug_shape_id: 4,
      color: "Yellow",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Tramadol",
      generic_drug: "Tramadol Hydrochloride",
      description: "Opioid analgesic used to treat moderate to severe pain.",
      dosage: 50,
      unit_measurement: "mg",
      type: "Oral",
      drug_shape_id: 4,
      color: "White",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Cephalexin",
      generic_drug: "Cephalexin",
      description: "Antibiotic used to treat various bacterial infections.",
      dosage: 500,
      unit_measurement: "mg",
      type: "Oral",
      drug_shape_id: 2,
      color: "Capsule: Blue/White; Tablet: White",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Ciprofloxacin",
      generic_drug: "Ciprofloxacin Hydrochloride",
      description: "Antibiotic used to treat various bacterial infections.",
      dosage: 500,
      unit_measurement: "mg",
      type: "Oral",
      drug_shape_id: 4,
      color: "White",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Prednisone",
      generic_drug: "Prednisone",
      description: "Corticosteroid used to reduce inflammation and suppress the immune system.",
      dosage: 10,
      unit_measurement: "mg",
      type: "Oral",
      drug_shape_id: 4,
      color: "White",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Metronidazole",
      generic_drug: "Metronidazole",
      description: "Antibiotic and antiprotozoal agent used to treat various infections.",
      dosage: 250,
      unit_measurement: "mg",
      type: "Oral",
      drug_shape_id: 4,
      color: "White",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Doxycycline",
      generic_drug: "Doxycycline Hyclate",
      description: "Antibiotic used to treat various bacterial infections.",
      dosage: 100,
      unit_measurement: "mg",
      type: "Oral",
      drug_shape_id: 4,
      color: "Yellow",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Azithromycin",
      generic_drug: "Azithromycin",
      description: "Antibiotic used to treat various bacterial infections.",
      dosage: 250,
      unit_measurement: "mg",
      type: "Oral",
      drug_shape_id: 4,
      color: "White",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Cetirizine",
      generic_drug: "Cetirizine Hydrochloride",
      description: "Antihistamine used to treat allergy symptoms.",
      dosage: 10,
      unit_measurement: "mg",
      type: "Oral",
      drug_shape_id: 4,
      color: "White",
      created_at: new Date(),
      updated_at: new Date(),
    },
  ]);

  for (let i = 0; i < 100; i++) {
    const firstName_data = faker.person.firstName();
    const lastName_data = faker.person.lastName();
    const gender_data = faker.person.sex();
    const phone_data = faker.phone.number();
    
    const fakeId = faker.number.int();
    await knex("patient").insert([
      {
        firstName: firstName_data,
        lastName: lastName_data,
        gender: gender_data,
        blood: "O",
        password: await hashPassword("t1"),
        hkid: `Y123456${i}`,
        birth_date: new Date("1980-01-01"),
        phone_number: phone_data,
        emergency_name: "Jane Doe",
        emergency_contact: phone_data,
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);
  }
  
  // let phone_data = faker.phone.number();
  
  // await knex("patient").insert([
  //   {
  //     firstName: "test1",
  //     lastName: "test1",
  //     gender: "male",
  //     blood: "O",
  //     password: await hashPassword("t2"),
  //     hkid: "Y1234568",
  //     birth_date: new Date("1980-01-01"),
  //     phone_number: phone_data,
  //     emergency_name: "Jane Doe",
  //     emergency_contact: phone_data,
  //     created_at: new Date(),
  //     updated_at: new Date(),
  //   },
  // ]);

  await knex("diagnosis").insert([
    {
      name: "Common Cold",
      doctor_id: 1,
      patient_id: 1,
      remarks: "Typical cold symptoms, no additional concerns.",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "High Blood Pressure",
      doctor_id: 2,
      patient_id: 3,
      remarks: "Patient has elevated blood pressure, monitoring required.",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Low Blood Pressure",
      doctor_id: 2,
      patient_id: 1,
      remarks: "Patient has elevated blood pressure, monitoring required.",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "High Blood Pressure",
      doctor_id: 2,
      patient_id: 2,
      remarks: "Patient has elevated blood pressure, monitoring required.",
      created_at: new Date(),
      updated_at: new Date(),
    },
  ]);

  await knex("drug_instruction").insert([
    {
      medicine_id: 1,
      diagnosis_id: 1,
      unit_measurement:"g" ,
      total_quantity: 30,
      method: "Oral",
      taken_count_today: 0,
      taken_count: 3,
      period_day: 10,
      period_hr: 3,
      frequency_per_day: 3,
      dosage_per_serving: 1,
      remarks: "Take 1 tablet 3 times a day with food.",
      send_at: new Date(),
      taken: false,
      taken_at: null
    },
    {
      medicine_id: 2,
      diagnosis_id: 1,
      unit_measurement:"g" ,
      total_quantity: 777,
      method: "Oral",
      taken_count_today: 0,
      taken_count: 10,
      period_day: 365,
      period_hr: 3,
      frequency_per_day: 2,
      dosage_per_serving: 1,
      remarks: "Take 1 tablet 3 times a day with food.",
      send_at: new Date(),
      taken: false,
      taken_at: null
    },
    {
      medicine_id: 2,
      diagnosis_id: 2,
      unit_measurement:"g" ,
      total_quantity: 60,
      method: "Oral",
      taken_count_today: 0,
      taken_count: 1,
      period_day: 30,
      period_hr: 3,
      frequency_per_day: 1,
      dosage_per_serving: 1,
      remarks: "Take 1 tablet once a day with food.",
      send_at: new Date(),
      taken: false,
      taken_at: null
    },

  ]);

  await knex("notification").insert([
    {
      patient_id: 1,
      drug_instruction_id: 1,
    },
    {
      patient_id: 2,
      drug_instruction_id: 2,
    },
  ]);
}
